testFetch:
		g++ -o fetch fetch.cpp

main:
		g++ -Wall -std=c++17 -o main vectorProcessor.cpp main.cpp fetch.cpp decoder.cpp execute.cpp alu.cpp fetch_decoder_register.cpp decoder_execute_register.cpp register_exe_mem.cpp memory.cpp
